CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "CierresCaja" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "Total" numeric NOT NULL,
    "ArchivoExcelUrl" text NOT NULL,
    CONSTRAINT "PK_CierresCaja" PRIMARY KEY ("Id")
);

CREATE TABLE "Clients" (
    "Id" uuid NOT NULL,
    "NombreComercial" text NOT NULL,
    "Subdominio" text NOT NULL,
    "Plan" text NOT NULL,
    "ModoSandbox" boolean NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaActivacion" timestamp with time zone NOT NULL,
    "ConfiguracionJson" text,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("Id")
);

CREATE TABLE "ConfiguracionesCatalogo" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "LogoClienteUrl" text NOT NULL,
    "ColorAcento" text NOT NULL,
    "MensajeBienvenida" text NOT NULL,
    "WhatsAppContacto" text,
    "PlantillaPublicacion" text,
    CONSTRAINT "PK_ConfiguracionesCatalogo" PRIMARY KEY ("Id")
);

CREATE TABLE "ConsumoRecursos" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "MbUsados" double precision NOT NULL,
    "AnchoBandaMb" double precision NOT NULL,
    "FechaActualizacion" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ConsumoRecursos" PRIMARY KEY ("Id")
);

CREATE TABLE "Empleados" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Nombre" text NOT NULL,
    "Correo" text,
    "Telefono" text,
    "Cargo" text NOT NULL,
    "AvatarUrl" text,
    "FechaIngreso" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_Empleados" PRIMARY KEY ("Id")
);

CREATE TABLE "Encuestas" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Nombre" text NOT NULL,
    "Tipo" text NOT NULL,
    "Activa" boolean NOT NULL,
    "BrandingJson" text,
    CONSTRAINT "PK_Encuestas" PRIMARY KEY ("Id")
);

CREATE TABLE "Formularios" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Nombre" text NOT NULL,
    "Tipo" text NOT NULL,
    "Activo" boolean NOT NULL,
    "PlanRequerido" text,
    CONSTRAINT "PK_Formularios" PRIMARY KEY ("Id")
);

CREATE TABLE "GruposTrabajo" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Nombre" text NOT NULL,
    "Descripcion" text,
    CONSTRAINT "PK_GruposTrabajo" PRIMARY KEY ("Id")
);

CREATE TABLE "HistorialCuentas" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "TipoEvento" text NOT NULL,
    "Nota" text,
    "Fecha" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HistorialCuentas" PRIMARY KEY ("Id")
);

CREATE TABLE "LogsModulo" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Modulo" text NOT NULL,
    "TipoEvento" text NOT NULL,
    "Detalle" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LogsModulo" PRIMARY KEY ("Id")
);

CREATE TABLE "Mesas" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Zona" text NOT NULL,
    "Numero" integer NOT NULL,
    "Estado" text NOT NULL,
    CONSTRAINT "PK_Mesas" PRIMARY KEY ("Id")
);

CREATE TABLE "NotasInternas" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "UsuarioGeshk" text NOT NULL,
    "Contenido" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_NotasInternas" PRIMARY KEY ("Id")
);

CREATE TABLE "Ordenes" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "UserId" uuid,
    "Fecha" timestamp with time zone NOT NULL,
    "Estado" text NOT NULL,
    "Total" numeric NOT NULL,
    CONSTRAINT "PK_Ordenes" PRIMARY KEY ("Id")
);

CREATE TABLE "PlanModules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Plan" text NOT NULL,
    "ModuleKey" text NOT NULL,
    "Permitido" boolean NOT NULL,
    CONSTRAINT "PK_PlanModules" PRIMARY KEY ("Id")
);

CREATE TABLE "ProductosCatalogo" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "ProductoId" uuid,
    "Nombre" text NOT NULL,
    "Nota" text,
    "Precio" numeric,
    "Visible" boolean NOT NULL,
    "Destacado" boolean NOT NULL,
    CONSTRAINT "PK_ProductosCatalogo" PRIMARY KEY ("Id")
);

CREATE TABLE "ProductosPOS" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Nombre" text NOT NULL,
    "Precio" numeric NOT NULL,
    CONSTRAINT "PK_ProductosPOS" PRIMARY KEY ("Id")
);

CREATE TABLE "Proveedores" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Nombre" text NOT NULL,
    "Telefono" text,
    "Correo" text,
    "Direccion" text,
    CONSTRAINT "PK_Proveedores" PRIMARY KEY ("Id")
);

CREATE TABLE "Modules" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" uuid NOT NULL,
    "ModuleKey" text NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_Modules" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Modules_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "NombreCompleto" text NOT NULL,
    "Correo" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Rol" text NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Asistencias" (
    "Id" uuid NOT NULL,
    "EmpleadoId" uuid NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "Tipo" text NOT NULL,
    "Observacion" text,
    "Usuario" text NOT NULL,
    CONSTRAINT "PK_Asistencias" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Asistencias_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Disponibilidades" (
    "Id" uuid NOT NULL,
    "EmpleadoId" uuid NOT NULL,
    "FechasBloqueadasJson" text NOT NULL,
    "VacacionesJson" text NOT NULL,
    CONSTRAINT "PK_Disponibilidades" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Disponibilidades_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE
);

CREATE TABLE "HistorialEmpleados" (
    "Id" uuid NOT NULL,
    "EmpleadoId" uuid NOT NULL,
    "Accion" text NOT NULL,
    "Comentario" text NOT NULL,
    "RegistradoPor" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_HistorialEmpleados" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HistorialEmpleados_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE
);

CREATE TABLE "HorariosSemanales" (
    "Id" uuid NOT NULL,
    "EmpleadoId" uuid NOT NULL,
    "DiaSemana" integer NOT NULL,
    "HoraInicio" interval NOT NULL,
    "HoraFin" interval NOT NULL,
    "Grupo" text NOT NULL,
    "Ubicacion" text,
    CONSTRAINT "PK_HorariosSemanales" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HorariosSemanales_Empleados_EmpleadoId" FOREIGN KEY ("EmpleadoId") REFERENCES "Empleados" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ConfiguracionesEncuesta" (
    "Id" uuid NOT NULL,
    "EncuestaId" uuid NOT NULL,
    "Visibilidad" text NOT NULL,
    "ActivarQR" boolean NOT NULL,
    "ActivarPostVenta" boolean NOT NULL,
    "ActivarPostCita" boolean NOT NULL,
    CONSTRAINT "PK_ConfiguracionesEncuesta" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConfiguracionesEncuesta_Encuestas_EncuestaId" FOREIGN KEY ("EncuestaId") REFERENCES "Encuestas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Preguntas" (
    "Id" uuid NOT NULL,
    "EncuestaId" uuid NOT NULL,
    "Texto" text NOT NULL,
    "Tipo" text NOT NULL,
    "Requerida" boolean NOT NULL,
    CONSTRAINT "PK_Preguntas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Preguntas_Encuestas_EncuestaId" FOREIGN KEY ("EncuestaId") REFERENCES "Encuestas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CamposPersonalizados" (
    "Id" uuid NOT NULL,
    "FormularioId" uuid NOT NULL,
    "Etiqueta" text NOT NULL,
    "Tipo" text NOT NULL,
    "Requerido" boolean NOT NULL,
    CONSTRAINT "PK_CamposPersonalizados" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CamposPersonalizados_Formularios_FormularioId" FOREIGN KEY ("FormularioId") REFERENCES "Formularios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Citas" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "FormularioId" uuid NOT NULL,
    "ClienteNombre" text NOT NULL,
    "Telefono" text NOT NULL,
    "Correo" text,
    "Fecha" timestamp with time zone NOT NULL,
    "Hora" interval NOT NULL,
    "Estado" text NOT NULL,
    "ObservacionesInternas" text,
    CONSTRAINT "PK_Citas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Citas_Formularios_FormularioId" FOREIGN KEY ("FormularioId") REFERENCES "Formularios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ConfiguracionesAgenda" (
    "Id" uuid NOT NULL,
    "FormularioId" uuid NOT NULL,
    "DiasActivosJson" text NOT NULL,
    "ExcepcionesJson" text NOT NULL,
    "HorarioInicio" interval NOT NULL,
    "HorarioFin" interval NOT NULL,
    "IntervaloMinutos" integer NOT NULL,
    CONSTRAINT "PK_ConfiguracionesAgenda" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConfiguracionesAgenda_Formularios_FormularioId" FOREIGN KEY ("FormularioId") REFERENCES "Formularios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ComprobantesPago" (
    "Id" uuid NOT NULL,
    "OrdenId" uuid NOT NULL,
    "UrlArchivo" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ComprobantesPago" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ComprobantesPago_Ordenes_OrdenId" FOREIGN KEY ("OrdenId") REFERENCES "Ordenes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ItemsOrden" (
    "Id" uuid NOT NULL,
    "OrdenId" uuid NOT NULL,
    "ProductoNombre" text NOT NULL,
    "Cantidad" integer NOT NULL,
    "PrecioUnitario" numeric NOT NULL,
    CONSTRAINT "PK_ItemsOrden" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ItemsOrden_Ordenes_OrdenId" FOREIGN KEY ("OrdenId") REFERENCES "Ordenes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MetodosPago" (
    "Id" uuid NOT NULL,
    "OrdenId" uuid NOT NULL,
    "Tipo" text NOT NULL,
    "Referencia" text,
    CONSTRAINT "PK_MetodosPago" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MetodosPago_Ordenes_OrdenId" FOREIGN KEY ("OrdenId") REFERENCES "Ordenes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Promociones" (
    "Id" uuid NOT NULL,
    "ProductoCatalogoId" uuid NOT NULL,
    "Titulo" text NOT NULL,
    "DescripcionCorta" text NOT NULL,
    "Activa" boolean NOT NULL,
    "FechaPublicacion" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Promociones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Promociones_ProductosCatalogo_ProductoCatalogoId" FOREIGN KEY ("ProductoCatalogoId") REFERENCES "ProductosCatalogo" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Publicaciones" (
    "Id" uuid NOT NULL,
    "ProductoCatalogoId" uuid NOT NULL,
    "Fondo" text NOT NULL,
    "TextoExtra" text,
    "UrlImagenGenerada" text NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Publicaciones" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Publicaciones_ProductosCatalogo_ProductoCatalogoId" FOREIGN KEY ("ProductoCatalogoId") REFERENCES "ProductosCatalogo" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Productos" (
    "Id" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Nombre" text NOT NULL,
    "PrecioVenta" numeric NOT NULL,
    "Costo" numeric NOT NULL,
    "Stock" integer NOT NULL,
    "StockMinimo" integer NOT NULL,
    "Visible" boolean NOT NULL,
    "ProveedorId" uuid,
    CONSTRAINT "PK_Productos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Productos_Proveedores_ProveedorId" FOREIGN KEY ("ProveedorId") REFERENCES "Proveedores" ("Id")
);

CREATE TABLE "LogsAcceso" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Accion" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "IpOrigen" text,
    "Modulo" text,
    CONSTRAINT "PK_LogsAcceso" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LogsAcceso_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Respuestas" (
    "Id" uuid NOT NULL,
    "EncuestaId" uuid NOT NULL,
    "PreguntaId" uuid NOT NULL,
    "RespuestaTexto" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "CanalOrigen" text NOT NULL,
    CONSTRAINT "PK_Respuestas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Respuestas_Encuestas_EncuestaId" FOREIGN KEY ("EncuestaId") REFERENCES "Encuestas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Respuestas_Preguntas_PreguntaId" FOREIGN KEY ("PreguntaId") REFERENCES "Preguntas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "HistorialCitas" (
    "Id" uuid NOT NULL,
    "CitaId" uuid NOT NULL,
    "Accion" text NOT NULL,
    "Usuario" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "Comentario" text,
    CONSTRAINT "PK_HistorialCitas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_HistorialCitas_Citas_CitaId" FOREIGN KEY ("CitaId") REFERENCES "Citas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AlertasStock" (
    "Id" uuid NOT NULL,
    "ProductoId" uuid NOT NULL,
    "Notificado" boolean NOT NULL,
    "FechaUltimaAlerta" timestamp with time zone,
    CONSTRAINT "PK_AlertasStock" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AlertasStock_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EntradasInventario" (
    "Id" uuid NOT NULL,
    "ProductoId" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Cantidad" integer NOT NULL,
    "Tipo" text NOT NULL,
    "Usuario" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EntradasInventario" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EntradasInventario_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "SalidasInventario" (
    "Id" uuid NOT NULL,
    "ProductoId" uuid NOT NULL,
    "ClientId" uuid NOT NULL,
    "Cantidad" integer NOT NULL,
    "Tipo" text NOT NULL,
    "ModuloOrigen" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_SalidasInventario" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SalidasInventario_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AlertasStock_ProductoId" ON "AlertasStock" ("ProductoId");

CREATE INDEX "IX_Asistencias_EmpleadoId" ON "Asistencias" ("EmpleadoId");

CREATE INDEX "IX_CamposPersonalizados_FormularioId" ON "CamposPersonalizados" ("FormularioId");

CREATE INDEX "IX_Citas_FormularioId" ON "Citas" ("FormularioId");

CREATE INDEX "IX_ComprobantesPago_OrdenId" ON "ComprobantesPago" ("OrdenId");

CREATE UNIQUE INDEX "IX_ConfiguracionesAgenda_FormularioId" ON "ConfiguracionesAgenda" ("FormularioId");

CREATE INDEX "IX_ConfiguracionesEncuesta_EncuestaId" ON "ConfiguracionesEncuesta" ("EncuestaId");

CREATE INDEX "IX_Disponibilidades_EmpleadoId" ON "Disponibilidades" ("EmpleadoId");

CREATE INDEX "IX_EntradasInventario_ProductoId" ON "EntradasInventario" ("ProductoId");

CREATE INDEX "IX_HistorialCitas_CitaId" ON "HistorialCitas" ("CitaId");

CREATE INDEX "IX_HistorialEmpleados_EmpleadoId" ON "HistorialEmpleados" ("EmpleadoId");

CREATE INDEX "IX_HorariosSemanales_EmpleadoId" ON "HorariosSemanales" ("EmpleadoId");

CREATE INDEX "IX_ItemsOrden_OrdenId" ON "ItemsOrden" ("OrdenId");

CREATE INDEX "IX_LogsAcceso_UserId" ON "LogsAcceso" ("UserId");

CREATE INDEX "IX_MetodosPago_OrdenId" ON "MetodosPago" ("OrdenId");

CREATE INDEX "IX_Modules_ClientId" ON "Modules" ("ClientId");

CREATE INDEX "IX_Preguntas_EncuestaId" ON "Preguntas" ("EncuestaId");

CREATE INDEX "IX_Productos_ProveedorId" ON "Productos" ("ProveedorId");

CREATE INDEX "IX_Promociones_ProductoCatalogoId" ON "Promociones" ("ProductoCatalogoId");

CREATE INDEX "IX_Publicaciones_ProductoCatalogoId" ON "Publicaciones" ("ProductoCatalogoId");

CREATE INDEX "IX_Respuestas_EncuestaId" ON "Respuestas" ("EncuestaId");

CREATE INDEX "IX_Respuestas_PreguntaId" ON "Respuestas" ("PreguntaId");

CREATE INDEX "IX_SalidasInventario_ProductoId" ON "SalidasInventario" ("ProductoId");

CREATE INDEX "IX_Users_ClientId" ON "Users" ("ClientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250515183955_InitialCreate', '9.0.5');

COMMIT;

